
// This file has been generated by the GUI designer. Do not modify.
namespace DownloadManager
{
	public partial class SettingsDialog
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.CheckButton chk_load_on_startup;
		private global::Gtk.CheckButton chk_start_minimized;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.CheckButton chk_minimize_to_tray;
		private global::Gtk.CheckButton chk_minimize_on_close;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.Table table1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.SpinButton sb_exit_time;
		private global::Gtk.SpinButton sb_launch_download_time;
		private global::Gtk.SpinButton sb_shutdown_time;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label8;
		private global::Gtk.SpinButton sb_auto_save_timeout;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.VBox vbox6;
		private global::Gtk.RadioButton rb_group_auto;
		private global::Gtk.HBox hbox2;
		private global::Gtk.RadioButton rb_group_manual;
		private global::Gtk.ComboBox cb_groups;
		private global::Gtk.Label GtkLabel9;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Frame frame5;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Table table2;
		private global::Gtk.Entry entry4;
		private global::Gtk.Entry entryGroupName;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button cmdNewGroup;
		private global::Gtk.Label GtkLabel12;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label7;
		private global::Gtk.Entry entry5;
		private global::Gtk.Label label9;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.VBox vbox8;
		private global::Gtk.CheckButton chkHTTPProxy;
		private global::Gtk.Frame httpFrame;
		private global::Gtk.VBox vbox9;
		private global::Gtk.CheckButton chkAllHTTP;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.Table table3;
		private global::Gtk.Entry entryHTTPAddress;
		private global::Gtk.Entry entryHTTPPassword;
		private global::Gtk.Entry entryHTTPUserName;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.SpinButton sbHTTPPort;
		private global::Gtk.Label ll;
		private global::Gtk.CheckButton chkFTPProxy;
		private global::Gtk.Frame ftpFrame;
		private global::Gtk.VBox vbox10;
		private global::Gtk.CheckButton chkAllFTP;
		private global::Gtk.Alignment GtkAlignment7;
		private global::Gtk.Table table4;
		private global::Gtk.Entry entryFTPAddress;
		private global::Gtk.Entry entryFTPPassword;
		private global::Gtk.Entry entryFTPUserName;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.SpinButton sbFTPPort;
		private global::Gtk.Label hh;
		private global::Gtk.CheckButton chkSOCKSProxy;
		private global::Gtk.Frame socksFrame;
		private global::Gtk.VBox vbox11;
		private global::Gtk.CheckButton chkAllSOCKS;
		private global::Gtk.Alignment GtkAlignment8;
		private global::Gtk.Table table5;
		private global::Gtk.Entry entrySOCKSAddress;
		private global::Gtk.Entry entrySOCKSPassword;
		private global::Gtk.Entry entrySOCKSUserName;
		private global::Gtk.Label label21;
		private global::Gtk.Label label22;
		private global::Gtk.Label label23;
		private global::Gtk.Label label24;
		private global::Gtk.SpinButton sbSOCKSPort;
		private global::Gtk.Label hhl;
		private global::Gtk.Label label12;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DownloadManager.SettingsDialog
			this.Name = "DownloadManager.SettingsDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DownloadManager.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.chk_load_on_startup = new global::Gtk.CheckButton ();
			this.chk_load_on_startup.CanFocus = true;
			this.chk_load_on_startup.Name = "chk_load_on_startup";
			this.chk_load_on_startup.Label = global::Mono.Unix.Catalog.GetString ("Load on startup");
			this.chk_load_on_startup.DrawIndicator = true;
			this.chk_load_on_startup.UseUnderline = true;
			this.vbox3.Add (this.chk_load_on_startup);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.chk_load_on_startup]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.chk_start_minimized = new global::Gtk.CheckButton ();
			this.chk_start_minimized.CanFocus = true;
			this.chk_start_minimized.Name = "chk_start_minimized";
			this.chk_start_minimized.Label = global::Mono.Unix.Catalog.GetString ("Start Minimized");
			this.chk_start_minimized.Active = true;
			this.chk_start_minimized.DrawIndicator = true;
			this.chk_start_minimized.UseUnderline = true;
			this.vbox3.Add (this.chk_start_minimized);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.chk_start_minimized]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.GtkAlignment2.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Startup");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chk_minimize_to_tray = new global::Gtk.CheckButton ();
			this.chk_minimize_to_tray.CanFocus = true;
			this.chk_minimize_to_tray.Name = "chk_minimize_to_tray";
			this.chk_minimize_to_tray.Label = global::Mono.Unix.Catalog.GetString ("Minimize to tray");
			this.chk_minimize_to_tray.DrawIndicator = true;
			this.chk_minimize_to_tray.UseUnderline = true;
			this.vbox4.Add (this.chk_minimize_to_tray);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chk_minimize_to_tray]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chk_minimize_on_close = new global::Gtk.CheckButton ();
			this.chk_minimize_on_close.CanFocus = true;
			this.chk_minimize_on_close.Name = "chk_minimize_on_close";
			this.chk_minimize_on_close.Label = global::Mono.Unix.Catalog.GetString ("Minimize on close");
			this.chk_minimize_on_close.DrawIndicator = true;
			this.chk_minimize_on_close.UseUnderline = true;
			this.vbox4.Add (this.chk_minimize_on_close);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chk_minimize_on_close]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.GtkAlignment3.Add (this.vbox4);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("System");
			this.GtkLabel5.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel5;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(13));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Launch Download");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Exit");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Shutdown");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sb_exit_time = new global::Gtk.SpinButton (0, 100, 1);
			this.sb_exit_time.CanFocus = true;
			this.sb_exit_time.Name = "sb_exit_time";
			this.sb_exit_time.Adjustment.PageIncrement = 10;
			this.sb_exit_time.ClimbRate = 1;
			this.sb_exit_time.Numeric = true;
			this.table1.Add (this.sb_exit_time);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.sb_exit_time]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sb_launch_download_time = new global::Gtk.SpinButton (0, 100, 1);
			this.sb_launch_download_time.CanFocus = true;
			this.sb_launch_download_time.Name = "sb_launch_download_time";
			this.sb_launch_download_time.Adjustment.PageIncrement = 10;
			this.sb_launch_download_time.ClimbRate = 1;
			this.sb_launch_download_time.Numeric = true;
			this.table1.Add (this.sb_launch_download_time);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.sb_launch_download_time]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sb_shutdown_time = new global::Gtk.SpinButton (0, 100, 1);
			this.sb_shutdown_time.CanFocus = true;
			this.sb_shutdown_time.Name = "sb_shutdown_time";
			this.sb_shutdown_time.Adjustment.PageIncrement = 10;
			this.sb_shutdown_time.ClimbRate = 1;
			this.sb_shutdown_time.Numeric = true;
			this.table1.Add (this.sb_shutdown_time);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.sb_shutdown_time]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment4.Add (this.table1);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.Xalign = 0F;
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("Timeout on confirmations (in Seconds)");
			this.GtkLabel8.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel8;
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Autosave after every (in mins)");
			this.hbox1.Add (this.label8);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label8]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.sb_auto_save_timeout = new global::Gtk.SpinButton (0, 100, 1);
			this.sb_auto_save_timeout.CanFocus = true;
			this.sb_auto_save_timeout.Name = "sb_auto_save_timeout";
			this.sb_auto_save_timeout.Adjustment.PageIncrement = 10;
			this.sb_auto_save_timeout.ClimbRate = 1;
			this.sb_auto_save_timeout.Numeric = true;
			this.hbox1.Add (this.sb_auto_save_timeout);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.sb_auto_save_timeout]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			this.notebook1.Add (this.vbox2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.vbox2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.rb_group_auto = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Determine group automatically"));
			this.rb_group_auto.CanFocus = true;
			this.rb_group_auto.Name = "rb_group_auto";
			this.rb_group_auto.DrawIndicator = true;
			this.rb_group_auto.UseUnderline = true;
			this.rb_group_auto.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox6.Add (this.rb_group_auto);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.rb_group_auto]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.rb_group_manual = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Always use this group for new download"));
			this.rb_group_manual.CanFocus = true;
			this.rb_group_manual.Name = "rb_group_manual";
			this.rb_group_manual.DrawIndicator = true;
			this.rb_group_manual.UseUnderline = true;
			this.rb_group_manual.Group = this.rb_group_auto.Group;
			this.hbox2.Add (this.rb_group_manual);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.rb_group_manual]));
			w26.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cb_groups = global::Gtk.ComboBox.NewText ();
			this.cb_groups.Name = "cb_groups";
			this.hbox2.Add (this.cb_groups);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cb_groups]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox6.Add (this.hbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox2]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment5.Add (this.vbox6);
			this.frame4.Add (this.GtkAlignment5);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("Group for new download");
			this.GtkLabel9.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel9;
			this.vbox5.Add (this.frame4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame4]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.vbox5.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbuttonbox2]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 5;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.table2.Add (this.entry4);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry4]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryGroupName = new global::Gtk.Entry ();
			this.entryGroupName.CanFocus = true;
			this.entryGroupName.Name = "entryGroupName";
			this.entryGroupName.IsEditable = true;
			this.entryGroupName.InvisibleChar = '•';
			this.table2.Add (this.entryGroupName);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryGroupName]));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Group Name");
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Directory");
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table2]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.cmdNewGroup = new global::Gtk.Button ();
			this.cmdNewGroup.CanFocus = true;
			this.cmdNewGroup.Name = "cmdNewGroup";
			this.cmdNewGroup.UseUnderline = true;
			this.cmdNewGroup.Label = global::Mono.Unix.Catalog.GetString ("Create new group");
			this.hbuttonbox3.Add (this.cmdNewGroup);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.cmdNewGroup]));
			w38.Expand = false;
			w38.Fill = false;
			this.vbox7.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbuttonbox3]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.frame5.Add (this.vbox7);
			this.GtkLabel12 = new global::Gtk.Label ();
			this.GtkLabel12.Name = "GtkLabel12";
			this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("New Group");
			this.GtkLabel12.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel12;
			this.vbox5.Add (this.frame5);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame5]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Download To:");
			this.hbox4.Add (this.label7);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entry5 = new global::Gtk.Entry ();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.hbox4.Add (this.entry5);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entry5]));
			w43.Position = 1;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w45 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w45.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Group");
			this.notebook1.SetTabLabel (this.vbox5, this.label9);
			this.label9.ShowAll ();
			// Notebook tab
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.Visible = true;
			this.notebook1.Add (w46);
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Connection");
			this.notebook1.SetTabLabel (w46, this.label10);
			this.label10.ShowAll ();
			// Notebook tab
			global::Gtk.Label w47 = new global::Gtk.Label ();
			w47.Visible = true;
			this.notebook1.Add (w47);
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed Limits");
			this.notebook1.SetTabLabel (w47, this.label11);
			this.label11.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.chkHTTPProxy = new global::Gtk.CheckButton ();
			this.chkHTTPProxy.CanFocus = true;
			this.chkHTTPProxy.Name = "chkHTTPProxy";
			this.chkHTTPProxy.Label = global::Mono.Unix.Catalog.GetString ("HTTP Proxy");
			this.chkHTTPProxy.DrawIndicator = true;
			this.chkHTTPProxy.UseUnderline = true;
			this.vbox8.Add (this.chkHTTPProxy);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.chkHTTPProxy]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.httpFrame = new global::Gtk.Frame ();
			this.httpFrame.Name = "httpFrame";
			this.httpFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child httpFrame.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.chkAllHTTP = new global::Gtk.CheckButton ();
			this.chkAllHTTP.CanFocus = true;
			this.chkAllHTTP.Name = "chkAllHTTP";
			this.chkAllHTTP.Label = global::Mono.Unix.Catalog.GetString ("Use this proxy protocol for all servers");
			this.chkAllHTTP.DrawIndicator = true;
			this.chkAllHTTP.UseUnderline = true;
			this.vbox9.Add (this.chkAllHTTP);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.chkAllHTTP]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.entryHTTPAddress = new global::Gtk.Entry ();
			this.entryHTTPAddress.CanFocus = true;
			this.entryHTTPAddress.Name = "entryHTTPAddress";
			this.entryHTTPAddress.IsEditable = true;
			this.entryHTTPAddress.InvisibleChar = '•';
			this.table3.Add (this.entryHTTPAddress);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryHTTPAddress]));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryHTTPPassword = new global::Gtk.Entry ();
			this.entryHTTPPassword.CanFocus = true;
			this.entryHTTPPassword.Name = "entryHTTPPassword";
			this.entryHTTPPassword.IsEditable = true;
			this.entryHTTPPassword.Visibility = false;
			this.entryHTTPPassword.InvisibleChar = '•';
			this.table3.Add (this.entryHTTPPassword);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryHTTPPassword]));
			w51.TopAttach = ((uint)(1));
			w51.BottomAttach = ((uint)(2));
			w51.LeftAttach = ((uint)(3));
			w51.RightAttach = ((uint)(4));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryHTTPUserName = new global::Gtk.Entry ();
			this.entryHTTPUserName.CanFocus = true;
			this.entryHTTPUserName.Name = "entryHTTPUserName";
			this.entryHTTPUserName.IsEditable = true;
			this.entryHTTPUserName.InvisibleChar = '•';
			this.table3.Add (this.entryHTTPUserName);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryHTTPUserName]));
			w52.TopAttach = ((uint)(1));
			w52.BottomAttach = ((uint)(2));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name");
			this.table3.Add (this.label14);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table3 [this.label14]));
			w54.TopAttach = ((uint)(1));
			w54.BottomAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
			this.table3.Add (this.label15);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
			w55.LeftAttach = ((uint)(2));
			w55.RightAttach = ((uint)(3));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.LeftAttach = ((uint)(2));
			w56.RightAttach = ((uint)(3));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.sbHTTPPort = new global::Gtk.SpinButton (0, 100, 1);
			this.sbHTTPPort.CanFocus = true;
			this.sbHTTPPort.Name = "sbHTTPPort";
			this.sbHTTPPort.Adjustment.PageIncrement = 10;
			this.sbHTTPPort.ClimbRate = 1;
			this.sbHTTPPort.Numeric = true;
			this.table3.Add (this.sbHTTPPort);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table3 [this.sbHTTPPort]));
			w57.LeftAttach = ((uint)(3));
			w57.RightAttach = ((uint)(4));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment6.Add (this.table3);
			this.vbox9.Add (this.GtkAlignment6);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkAlignment6]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			this.httpFrame.Add (this.vbox9);
			this.ll = new global::Gtk.Label ();
			this.ll.Name = "ll";
			this.ll.LabelProp = global::Mono.Unix.Catalog.GetString ("HTTP Proxy");
			this.ll.UseMarkup = true;
			this.httpFrame.LabelWidget = this.ll;
			this.vbox8.Add (this.httpFrame);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.httpFrame]));
			w61.Position = 1;
			w61.Expand = false;
			w61.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.chkFTPProxy = new global::Gtk.CheckButton ();
			this.chkFTPProxy.CanFocus = true;
			this.chkFTPProxy.Name = "chkFTPProxy";
			this.chkFTPProxy.Label = global::Mono.Unix.Catalog.GetString ("FTP Proxy");
			this.chkFTPProxy.DrawIndicator = true;
			this.chkFTPProxy.UseUnderline = true;
			this.vbox8.Add (this.chkFTPProxy);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.chkFTPProxy]));
			w62.Position = 2;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.ftpFrame = new global::Gtk.Frame ();
			this.ftpFrame.Name = "ftpFrame";
			this.ftpFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child ftpFrame.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.chkAllFTP = new global::Gtk.CheckButton ();
			this.chkAllFTP.CanFocus = true;
			this.chkAllFTP.Name = "chkAllFTP";
			this.chkAllFTP.Label = global::Mono.Unix.Catalog.GetString ("Use this proxy protocol for all servers");
			this.chkAllFTP.DrawIndicator = true;
			this.chkAllFTP.UseUnderline = true;
			this.vbox10.Add (this.chkAllFTP);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.chkAllFTP]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.entryFTPAddress = new global::Gtk.Entry ();
			this.entryFTPAddress.CanFocus = true;
			this.entryFTPAddress.Name = "entryFTPAddress";
			this.entryFTPAddress.IsEditable = true;
			this.entryFTPAddress.InvisibleChar = '•';
			this.table4.Add (this.entryFTPAddress);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table4 [this.entryFTPAddress]));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entryFTPPassword = new global::Gtk.Entry ();
			this.entryFTPPassword.CanFocus = true;
			this.entryFTPPassword.Name = "entryFTPPassword";
			this.entryFTPPassword.IsEditable = true;
			this.entryFTPPassword.InvisibleChar = '•';
			this.table4.Add (this.entryFTPPassword);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table4 [this.entryFTPPassword]));
			w65.TopAttach = ((uint)(1));
			w65.BottomAttach = ((uint)(2));
			w65.LeftAttach = ((uint)(3));
			w65.RightAttach = ((uint)(4));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entryFTPUserName = new global::Gtk.Entry ();
			this.entryFTPUserName.CanFocus = true;
			this.entryFTPUserName.Name = "entryFTPUserName";
			this.entryFTPUserName.IsEditable = true;
			this.entryFTPUserName.InvisibleChar = '•';
			this.table4.Add (this.entryFTPUserName);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table4 [this.entryFTPUserName]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.table4.Add (this.label17);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table4 [this.label17]));
			w67.TopAttach = ((uint)(1));
			w67.BottomAttach = ((uint)(2));
			w67.LeftAttach = ((uint)(2));
			w67.RightAttach = ((uint)(3));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
			this.table4.Add (this.label18);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table4 [this.label18]));
			w68.LeftAttach = ((uint)(2));
			w68.RightAttach = ((uint)(3));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name");
			this.table4.Add (this.label19);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table4 [this.label19]));
			w69.TopAttach = ((uint)(1));
			w69.BottomAttach = ((uint)(2));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.table4.Add (this.label20);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table4 [this.label20]));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbFTPPort = new global::Gtk.SpinButton (0, 100, 1);
			this.sbFTPPort.CanFocus = true;
			this.sbFTPPort.Name = "sbFTPPort";
			this.sbFTPPort.Adjustment.PageIncrement = 10;
			this.sbFTPPort.ClimbRate = 1;
			this.sbFTPPort.Numeric = true;
			this.table4.Add (this.sbFTPPort);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table4 [this.sbFTPPort]));
			w71.LeftAttach = ((uint)(3));
			w71.RightAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment7.Add (this.table4);
			this.vbox10.Add (this.GtkAlignment7);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.GtkAlignment7]));
			w73.Position = 1;
			w73.Expand = false;
			w73.Fill = false;
			this.ftpFrame.Add (this.vbox10);
			this.hh = new global::Gtk.Label ();
			this.hh.Name = "hh";
			this.hh.LabelProp = global::Mono.Unix.Catalog.GetString ("FTP Proxy");
			this.hh.UseMarkup = true;
			this.ftpFrame.LabelWidget = this.hh;
			this.vbox8.Add (this.ftpFrame);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.ftpFrame]));
			w75.Position = 3;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.chkSOCKSProxy = new global::Gtk.CheckButton ();
			this.chkSOCKSProxy.CanFocus = true;
			this.chkSOCKSProxy.Name = "chkSOCKSProxy";
			this.chkSOCKSProxy.Label = global::Mono.Unix.Catalog.GetString ("SOCKS Proxy");
			this.chkSOCKSProxy.DrawIndicator = true;
			this.chkSOCKSProxy.UseUnderline = true;
			this.vbox8.Add (this.chkSOCKSProxy);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.chkSOCKSProxy]));
			w76.Position = 4;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.socksFrame = new global::Gtk.Frame ();
			this.socksFrame.Name = "socksFrame";
			this.socksFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child socksFrame.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.chkAllSOCKS = new global::Gtk.CheckButton ();
			this.chkAllSOCKS.CanFocus = true;
			this.chkAllSOCKS.Name = "chkAllSOCKS";
			this.chkAllSOCKS.Label = global::Mono.Unix.Catalog.GetString ("Use this proxy protocol for all servers");
			this.chkAllSOCKS.DrawIndicator = true;
			this.chkAllSOCKS.UseUnderline = true;
			this.vbox11.Add (this.chkAllSOCKS);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.chkAllSOCKS]));
			w77.Position = 0;
			w77.Expand = false;
			w77.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.entrySOCKSAddress = new global::Gtk.Entry ();
			this.entrySOCKSAddress.CanFocus = true;
			this.entrySOCKSAddress.Name = "entrySOCKSAddress";
			this.entrySOCKSAddress.IsEditable = true;
			this.entrySOCKSAddress.InvisibleChar = '•';
			this.table5.Add (this.entrySOCKSAddress);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table5 [this.entrySOCKSAddress]));
			w78.LeftAttach = ((uint)(1));
			w78.RightAttach = ((uint)(2));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entrySOCKSPassword = new global::Gtk.Entry ();
			this.entrySOCKSPassword.CanFocus = true;
			this.entrySOCKSPassword.Name = "entrySOCKSPassword";
			this.entrySOCKSPassword.IsEditable = true;
			this.entrySOCKSPassword.InvisibleChar = '•';
			this.table5.Add (this.entrySOCKSPassword);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table5 [this.entrySOCKSPassword]));
			w79.TopAttach = ((uint)(1));
			w79.BottomAttach = ((uint)(2));
			w79.LeftAttach = ((uint)(3));
			w79.RightAttach = ((uint)(4));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entrySOCKSUserName = new global::Gtk.Entry ();
			this.entrySOCKSUserName.CanFocus = true;
			this.entrySOCKSUserName.Name = "entrySOCKSUserName";
			this.entrySOCKSUserName.IsEditable = true;
			this.entrySOCKSUserName.InvisibleChar = '•';
			this.table5.Add (this.entrySOCKSUserName);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table5 [this.entrySOCKSUserName]));
			w80.TopAttach = ((uint)(1));
			w80.BottomAttach = ((uint)(2));
			w80.LeftAttach = ((uint)(1));
			w80.RightAttach = ((uint)(2));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Address");
			this.table5.Add (this.label21);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table5 [this.label21]));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name");
			this.table5.Add (this.label22);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table5 [this.label22]));
			w82.TopAttach = ((uint)(1));
			w82.BottomAttach = ((uint)(2));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
			this.table5.Add (this.label23);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table5 [this.label23]));
			w83.LeftAttach = ((uint)(2));
			w83.RightAttach = ((uint)(3));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xalign = 0F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.table5.Add (this.label24);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table5 [this.label24]));
			w84.TopAttach = ((uint)(1));
			w84.BottomAttach = ((uint)(2));
			w84.LeftAttach = ((uint)(2));
			w84.RightAttach = ((uint)(3));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.sbSOCKSPort = new global::Gtk.SpinButton (0, 100, 1);
			this.sbSOCKSPort.CanFocus = true;
			this.sbSOCKSPort.Name = "sbSOCKSPort";
			this.sbSOCKSPort.Adjustment.PageIncrement = 10;
			this.sbSOCKSPort.ClimbRate = 1;
			this.sbSOCKSPort.Numeric = true;
			this.table5.Add (this.sbSOCKSPort);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table5 [this.sbSOCKSPort]));
			w85.LeftAttach = ((uint)(3));
			w85.RightAttach = ((uint)(4));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment8.Add (this.table5);
			this.vbox11.Add (this.GtkAlignment8);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.GtkAlignment8]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			this.socksFrame.Add (this.vbox11);
			this.hhl = new global::Gtk.Label ();
			this.hhl.Name = "hhl";
			this.hhl.LabelProp = global::Mono.Unix.Catalog.GetString ("SOCKS Proxy");
			this.hhl.UseMarkup = true;
			this.socksFrame.LabelWidget = this.hhl;
			this.vbox8.Add (this.socksFrame);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.socksFrame]));
			w89.Position = 5;
			w89.Expand = false;
			w89.Fill = false;
			this.notebook1.Add (this.vbox8);
			global::Gtk.Notebook.NotebookChild w90 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox8]));
			w90.Position = 4;
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Proxy");
			this.notebook1.SetTabLabel (this.vbox8, this.label12);
			this.label12.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w91.Position = 0;
			// Internal child DownloadManager.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w92 = this.ActionArea;
			w92.Name = "dialog1_ActionArea";
			w92.Spacing = 10;
			w92.BorderWidth = ((uint)(5));
			w92.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w93 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w92 [this.buttonCancel]));
			w93.Expand = false;
			w93.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w94 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w92 [this.buttonOk]));
			w94.Position = 1;
			w94.Expand = false;
			w94.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 595;
			this.DefaultHeight = 527;
			this.Show ();
			this.cmdNewGroup.Clicked += new global::System.EventHandler (this.OnCmdNewGroupClicked);
			this.chkHTTPProxy.Toggled += new global::System.EventHandler (this.OnChkHTTPProxyToggled);
			this.chkAllHTTP.Toggled += new global::System.EventHandler (this.chkAllHTTPToggled);
			this.chkFTPProxy.Toggled += new global::System.EventHandler (this.OnChkFTPProxyToggled);
			this.chkAllFTP.Toggled += new global::System.EventHandler (this.chkAllFTPToggled);
			this.chkSOCKSProxy.Toggled += new global::System.EventHandler (this.OnChkSOCKSProxyToggled);
			this.chkAllSOCKS.Toggled += new global::System.EventHandler (this.chkAllSOCKSToggled);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
