
// This file has been generated by the GUI designer. Do not modify.
namespace DownloadManager
{
	public partial class ProgressWindow
	{
		private global::Gtk.VBox dialog1_VBox;
		private global::Gtk.Table table2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label22;
		private global::Gtk.Label label23;
		private global::Gtk.Label label25;
		private global::Gtk.Label label27;
		private global::Gtk.Label label30;
		private global::Gtk.Label lblAddress;
		private global::Gtk.Label lblDestination;
		private global::Gtk.Label lblResumeSupport;
		private global::Gtk.Label lblSpeed;
		private global::Gtk.Label lblStatus;
		private global::Gtk.Label lblTimeLeft;
		private global::Gtk.CheckButton chkLaunchDownload;
		private global::Gtk.CheckButton chkShutdown;
		private global::DownloadManager.DMProgressBar dmprogressbar;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button button78;
		private global::Gtk.Button button77;
		private global::Gtk.Button button76;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DownloadManager.ProgressWindow
			this.Name = "DownloadManager.ProgressWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProgressWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DownloadManager.ProgressWindow.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox ();
			this.dialog1_VBox.Name = "dialog1_VBox";
			this.dialog1_VBox.Spacing = 6;
			this.dialog1_VBox.BorderWidth = ((uint)(7));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w1.TopAttach = ((uint)(3));
			w1.BottomAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Resume Support:");
			this.table2.Add (this.label22);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.label22]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Address:");
			this.table2.Add (this.label23);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.label23]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.Xalign = 0F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Destination:");
			this.table2.Add (this.label25);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.label25]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.Xalign = 0F;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed:");
			this.table2.Add (this.label27);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.label27]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.Xalign = 0F;
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Left:");
			this.table2.Add (this.label30);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.label30]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblAddress = new global::Gtk.Label ();
			this.lblAddress.Name = "lblAddress";
			this.lblAddress.Xalign = 0F;
			this.lblAddress.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.table2.Add (this.lblAddress);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblAddress]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblDestination = new global::Gtk.Label ();
			this.lblDestination.Name = "lblDestination";
			this.lblDestination.Xalign = 0F;
			this.lblDestination.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.table2.Add (this.lblDestination);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblDestination]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblResumeSupport = new global::Gtk.Label ();
			this.lblResumeSupport.Name = "lblResumeSupport";
			this.lblResumeSupport.Xalign = 0F;
			this.table2.Add (this.lblResumeSupport);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblResumeSupport]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblSpeed = new global::Gtk.Label ();
			this.lblSpeed.Name = "lblSpeed";
			this.lblSpeed.Xalign = 0F;
			this.table2.Add (this.lblSpeed);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblSpeed]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblStatus = new global::Gtk.Label ();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.Xalign = 0F;
			this.table2.Add (this.lblStatus);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblStatus]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblTimeLeft = new global::Gtk.Label ();
			this.lblTimeLeft.Name = "lblTimeLeft";
			this.lblTimeLeft.Xalign = 0F;
			this.table2.Add (this.lblTimeLeft);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblTimeLeft]));
			w12.TopAttach = ((uint)(5));
			w12.BottomAttach = ((uint)(6));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.dialog1_VBox.Add (this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.table2]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.chkLaunchDownload = new global::Gtk.CheckButton ();
			this.chkLaunchDownload.CanFocus = true;
			this.chkLaunchDownload.Name = "chkLaunchDownload";
			this.chkLaunchDownload.Label = global::Mono.Unix.Catalog.GetString ("Launch download automatically");
			this.chkLaunchDownload.DrawIndicator = true;
			this.chkLaunchDownload.UseUnderline = true;
			this.dialog1_VBox.Add (this.chkLaunchDownload);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.chkLaunchDownload]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.chkShutdown = new global::Gtk.CheckButton ();
			this.chkShutdown.CanFocus = true;
			this.chkShutdown.Name = "chkShutdown";
			this.chkShutdown.Label = global::Mono.Unix.Catalog.GetString ("Shutdown when done");
			this.chkShutdown.DrawIndicator = true;
			this.chkShutdown.UseUnderline = true;
			this.dialog1_VBox.Add (this.chkShutdown);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.chkShutdown]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dmprogressbar = new global::DownloadManager.DMProgressBar ();
			this.dmprogressbar.Name = "dmprogressbar";
			this.dialog1_VBox.Add (this.dmprogressbar);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.dmprogressbar]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.dialog1_VBox.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hseparator1]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button78 = new global::Gtk.Button ();
			this.button78.CanFocus = true;
			this.button78.Name = "button78";
			this.button78.UseUnderline = true;
			this.button78.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox1.Add (this.button78);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button78]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button77 = new global::Gtk.Button ();
			this.button77.CanFocus = true;
			this.button77.Name = "button77";
			this.button77.UseUnderline = true;
			this.button77.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox1.Add (this.button77);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button77]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button76 = new global::Gtk.Button ();
			this.button76.CanFocus = true;
			this.button76.Name = "button76";
			this.button76.UseUnderline = true;
			this.button76.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox1.Add (this.button76);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button76]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.dialog1_VBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbox1]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 5;
			w21.Expand = false;
			w21.Fill = false;
			this.Add (this.dialog1_VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 399;
			this.DefaultHeight = 305;
			this.Show ();
		}
	}
}
