
// This file has been generated by the GUI designer. Do not modify.
namespace DownloadManager
{
	public partial class CreateQueueDialog
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.Entry entryQueueName;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.RadioButton rbNow;
		private global::Gtk.RadioButton rbLater;
		private global::Gtk.RadioButton rbSchedule;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DownloadManager.CreateQueueDialog
			this.Name = "DownloadManager.CreateQueueDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create Queue");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DownloadManager.CreateQueueDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Queue Name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryQueueName = new global::Gtk.Entry ();
			this.entryQueueName.CanFocus = true;
			this.entryQueueName.Name = "entryQueueName";
			this.entryQueueName.IsEditable = true;
			this.entryQueueName.InvisibleChar = '•';
			this.hbox2.Add (this.entryQueueName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryQueueName]));
			w3.Position = 1;
			w1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rbNow = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Now"));
			this.rbNow.CanFocus = true;
			this.rbNow.Name = "rbNow";
			this.rbNow.DrawIndicator = true;
			this.rbNow.UseUnderline = true;
			this.rbNow.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox4.Add (this.rbNow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbNow]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rbLater = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Later"));
			this.rbLater.CanFocus = true;
			this.rbLater.Name = "rbLater";
			this.rbLater.DrawIndicator = true;
			this.rbLater.UseUnderline = true;
			this.rbLater.Group = this.rbNow.Group;
			this.vbox4.Add (this.rbLater);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbLater]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.rbSchedule = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Schedule"));
			this.rbSchedule.CanFocus = true;
			this.rbSchedule.Name = "rbSchedule";
			this.rbSchedule.DrawIndicator = true;
			this.rbSchedule.UseUnderline = true;
			this.rbSchedule.Group = this.rbNow.Group;
			this.vbox4.Add (this.rbSchedule);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbSchedule]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.GtkAlignment3.Add (this.vbox4);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			this.GtkLabel5.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel5;
			w1.Add (this.frame2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.frame2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child DownloadManager.CreateQueueDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("Create");
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 190;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.buttonOkClicked);
		}
	}
}
