
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action NewDownloadAction;
	private global::Gtk.Action AddExistingDownloadAction;
	private global::Gtk.Action toolbarNewDownload;
	private global::Gtk.Action toolbarAddDownload;
	private global::Gtk.Action mediaPlayAction;
	private global::Gtk.Action mediaPauseAction;
	private global::Gtk.Action cancelAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action findAction;
	private global::Gtk.Action preferencesAction;
	private global::Gtk.Action SpeedLowAction;
	private global::Gtk.Action SpeedMediumAction;
	private global::Gtk.Action SpeedFullAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::DownloadManager.DMCategoryTreeView dmCategoryTreeView;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::DownloadManager.DMDownloadTreeView dmDownloadTreeView;
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.NewDownloadAction = new global::Gtk.Action ("NewDownloadAction", global::Mono.Unix.Catalog.GetString ("New Download"), null, null);
		this.NewDownloadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Download");
		w1.Add (this.NewDownloadAction, null);
		this.AddExistingDownloadAction = new global::Gtk.Action ("AddExistingDownloadAction", global::Mono.Unix.Catalog.GetString ("Add Existing Download"), null, null);
		this.AddExistingDownloadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Existing Download");
		w1.Add (this.AddExistingDownloadAction, null);
		this.toolbarNewDownload = new global::Gtk.Action ("toolbarNewDownload", null, null, "gtk-new");
		w1.Add (this.toolbarNewDownload, null);
		this.toolbarAddDownload = new global::Gtk.Action ("toolbarAddDownload", null, null, "gtk-open");
		w1.Add (this.toolbarAddDownload, null);
		this.mediaPlayAction = new global::Gtk.Action ("mediaPlayAction", null, null, "gtk-media-play");
		w1.Add (this.mediaPlayAction, null);
		this.mediaPauseAction = new global::Gtk.Action ("mediaPauseAction", null, null, "gtk-media-pause");
		w1.Add (this.mediaPauseAction, null);
		this.cancelAction = new global::Gtk.Action ("cancelAction", null, null, "gtk-cancel");
		w1.Add (this.cancelAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.findAction = new global::Gtk.Action ("findAction", null, null, "gtk-find");
		w1.Add (this.findAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
		w1.Add (this.preferencesAction, null);
		this.SpeedLowAction = new global::Gtk.Action ("SpeedLowAction", global::Mono.Unix.Catalog.GetString ("Speed Low"), null, null);
		this.SpeedLowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Speed Low");
		w1.Add (this.SpeedLowAction, null);
		this.SpeedMediumAction = new global::Gtk.Action ("SpeedMediumAction", global::Mono.Unix.Catalog.GetString ("SpeedMedium"), null, null);
		this.SpeedMediumAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("SpeedMedium");
		w1.Add (this.SpeedMediumAction, null);
		this.SpeedFullAction = new global::Gtk.Action ("SpeedFullAction", global::Mono.Unix.Catalog.GetString ("SpeedFull"), null, null);
		this.SpeedFullAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("SpeedFull");
		w1.Add (this.SpeedFullAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewDownloadAction' action='NewDownloadAction'/><menuitem name='AddExistingDownloadAction' action='AddExistingDownloadAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='toolbarNewDownload' action='toolbarNewDownload'/><toolitem name='toolbarAddDownload' action='toolbarAddDownload'/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaPauseAction' action='mediaPauseAction'/><toolitem name='cancelAction' action='cancelAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='findAction' action='findAction'/><toolitem name='preferencesAction' action='preferencesAction'/><toolitem name='SpeedLowAction' action='SpeedLowAction'/><toolitem name='SpeedMediumAction' action='SpeedMediumAction'/><toolitem name='SpeedFullAction' action='SpeedFullAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 120;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 201;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.dmCategoryTreeView = new global::DownloadManager.DMCategoryTreeView ();
		this.dmCategoryTreeView.CanFocus = true;
		this.dmCategoryTreeView.Name = "dmCategoryTreeView";
		this.GtkScrolledWindow.Add (this.dmCategoryTreeView);
		this.hpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.dmDownloadTreeView = new global::DownloadManager.DMDownloadTreeView ();
		this.dmDownloadTreeView.CanFocus = true;
		this.dmDownloadTreeView.Name = "dmDownloadTreeView";
		this.GtkScrolledWindow1.Add (this.dmDownloadTreeView);
		this.hpaned1.Add (this.GtkScrolledWindow1);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 439;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.NewDownloadAction.Activated += new global::System.EventHandler (this.OnNewDownloadActivated);
		this.mediaPlayAction.Activated += new global::System.EventHandler (this.OnToolbarStartActivated);
		this.mediaPauseAction.Activated += new global::System.EventHandler (this.OnToolbarPauseActivated);
		this.cancelAction.Activated += new global::System.EventHandler (this.OnToolbarCancelActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnToolbarRestartActivated);
		this.findAction.Activated += new global::System.EventHandler (this.OnToolbarFindActivated);
		this.SpeedLowAction.Activated += new global::System.EventHandler (this.OnSpeedLowActivated);
		this.SpeedMediumAction.Activated += new global::System.EventHandler (this.OnSpeedMediumActivated);
		this.SpeedFullAction.Activated += new global::System.EventHandler (this.OnSpeedHighActivated);
		this.dmCategoryTreeView.RowActivated += new global::Gtk.RowActivatedHandler (this.dmCategoryTreeViewRowActivated);
		this.dmDownloadTreeView.RowActivated += new global::Gtk.RowActivatedHandler (this.dmDownloadTreeViewRowActivated);
	}
}
